services:
  # Backend Node.js / Express Service
  - type: web
    name: alumniconnect-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false

  # Frontend Static Web Site
  - type: web
    name: alumniconnect-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
