// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pooled connection via PgBouncer — used by the app at runtime
    url: process.env["DATABASE_URL"],
    // Direct (non-pooled) connection — required by Prisma migrate commands
    // Neon direct endpoint: hostname without "-pooler", no pgbouncer param
    directUrl: process.env["DIRECT_URL"],
  },
});

